In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('cleaned_kpmi_data.csv')
df.head()

,jobtitle,jobfield,scale_e,scale_i,scale_s,scale_n,scale_t,scale_f,scale_j,scale_p,psychotype,satisfied
0,HR manager,Staff and training,16,22,17,16,23,11,22,15,ISTJ,1
1,HR manager,Staff and training,28,6,14,18,20,16,20,15,ENTJ,0
2,HR manager,Staff and training,28,10,22,10,16,14,22,12,ESTJ,1
3,HR manager,Staff and training,24,10,16,17,13,23,31,3,ENFJ,0
4,HR manager,Staff and training,25,12,17,13,23,11,10,25,ESTP,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13499 entries, 0 to 13498
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   jobtitle    12621 non-null  object
 1   jobfield    13499 non-null  object
 2   scale_e     13499 non-null  int64
 3   scale_i     13499 non-null  int64
 4   scale_s     13499 non-null  int64
 5   scale_n     13499 non-null  int64
 6   scale_t     13499 non-null  int64
 7   scale_f     13499 non-null  int64
 8   scale_j     13499 non-null  int64
 9   scale_p     13499 non-null  int64
 10  psychotype  13499 non-null  object
 11  satisfied   13499 non-null  int64
dtypes: int64(9), object(3)
memory usage: 1.2+ MB

In [5]:
df.shape

(13499, 12)

In [6]:
df.describe(include='all')

,jobtitle,jobfield,scale_e,scale_i,scale_s,scale_n,scale_t,scale_f,scale_j,scale_p,psychotype,satisfied
count,12621,13499,13499.000000,13499.000000,13499.000000,13499.000000,13499.000000,13499.000000,13499.000000,13499.000000,13499,13499.000000
unique,68,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN
top,Student,Communication sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ESTJ,NaN
freq,1428,2203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3860,NaN
mean,NaN,NaN,20.391733,15.872213,18.358545,14.296837,20.483962,13.547448,21.123713,13.976887,NaN,0.676939
std,NaN,NaN,6.550919,6.513572,6.384925,6.003540,6.652640,6.121095,6.971628,7.107700,NaN,0.467663
min,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
25%,NaN,NaN,16.000000,11.000000,14.000000,10.000000,16.000000,9.000000,16.000000,8.000000,NaN,0.000000
50%,NaN,NaN,21.000000,16.000000,18.000000,14.000000,21.000000,13.000000,22.000000,13.000000,NaN,1.000000
75%,NaN,NaN,25.000000,21.000000,23.000000,18.000000,26.000000,18.000000,27.000000,19.000000,NaN,1.000000
max,NaN,NaN,35.000000,35.000000,35.000000,36.000000,35.000000,35.000000,35.000000,35.000000,NaN,1.000000